site_name: Doc Technique Lodel

pages:
- Accueil: 'index.md'
- Installation complète de Lodel: 'installer lodel.md'
- 'Architecture et organisation.md'
- 'Modèle éditorial.md'
- 'XML.md'
- 'Schéma TEI.md'
- 'Schéma METS.md'
- La chaine de publication XML (métopes): 'Métopes.md'
- La chaine de publication Word: 'Modèle de document pour Microsoft Word.md'
- 'Modèle de document Openoffice.md'
- Conversion de fichiers OTX: 'OTX.md'
- Les extensions (plugins): 'Plugins.md'
- 'Templates.md'
- 'Lodelscript.md'
