site_name: Doc Technique Lodel

pages:
- Accueil: 'index.md'
- Installation complète de Lodel: 'installer lodel.md'
- 'Architecture et organisation.md'
- 'Modèle éditorial.md'
- Contenus structurés:
  - 'Les-contenus-structurés/XML.md'
  - 'Les-contenus-structurés/Schéma TEI.md'
  - 'Les-contenus-structurés/Schéma METS.md'
 
- La chaine de publication Word:
  - La chaine de publication XML (métopes): 'Métopes.md'
  - 'La-chaine-de-publication-Word/Modèle de document Microsoft Word.md'
  - 'La-chaine-de-publication-Word/Modèle de document Openoffice.md'
  - Conversion de fichiers OTX: 'La-chaine-de-publication-Word/OTX.md'

- Les extensions (plugins): 'Plugins.md'
- 'Les-templates/Templates.md'
- 'Les-templates/Lodelscript.md'
- 'Configurer-Lodel/Présentation de Lodel.md'
- 'Configurer-Lodel/Principales notions.md'
- 'Configurer-Lodel/Fonctionnalités.md'
- 'Configurer-Lodel/Administrateur.md'
- 'Configurer-Lodel/Editeur.md'
