site_name: Doc Technique Lodel

pages:
- Accueil: 'index.md'
- Installation complète de Lodel: 'installer lodel.md'
- 'Architecture et organisation.md'
- 'Modèle éditorial.md'
- 'Les contenus structurés/XML.md'
- 'Les contenus structurés/Schéma TEI.md'
- 'Les contenus structurés/Schéma METS.md'
- La chaine de publication XML (métopes): 'Métopes.md'
- 'La chaine de publication Word/Modèle de document pour Microsoft Word.md'
- 'La chaine de publication Word/Modèle de document pour Openoffice.md'
- Conversion de fichiers OTX: 'OTX.md'
- Les extensions (plugins): 'Plugins.md'
- 'Les templates/Templates.md'
- 'Les templates/Lodelscript.md'
