site_name: Doc Technique Lodel

pages:
- Accueil: 'index.md'
- Installation complète de Lodel: 'installer lodel.md'
- 'Modèle éditorial.md'
- Les contenus structurés: 'Contenus structurés.md'
- La chaine de publication XML (métopes): 'Métopes.md'
- La chaine de publication Word: 'Modèle de document pour Microsoft Word.md'
- Conversion de fichiers OTX: 'OTX.md'
- Les extensions (plugins): 'Plugins.md'
- Templates: 'Lodelscript.md'
- 'Glossaire.md'
