site_name: Doc Technique Lodel

pages:
- Accueil: 'docs/index.md'
- 'docs/Glossaire.md'
- 'docs/Doc technique/installer lodel.md'
- 'docs/Modèle éditorial.md'
- 'docs/TEI.md'
- Lodel et Word
  - 'docs/OTX.md'
  - 'docs/Modèle de document pour Microsoft Word.md"
  - 'docs/Modèle de document pour LibreOffice.md'
- Imports de collections (livres, numéro de revue): 'docs/METS.md'
- Les extensions (plugins): 'docs/Plugins.md'