site_name: Doc Technique Lodel

pages:
- Accueil: 'index.md'
- Installation complète de Lodel: 'installer lodel.md'
- Les données de Lodel: 'Modèle éditorial.md'
- Imports de collections (livres, numéro de revue): 'METS.md'
- La chaine de publication Word: 'Modèle de document pour Microsoft Word.md'
- 'Modèle de document pour LibreOffice.md'
- Conversion de fichiers OTX: 'OTX.md'
- Les extensions (plugins): 'Plugins.md'
- 'Templates.md'
- 'Lodelscript.md'
- 'Glossaire.md'
