site_name: Doc Technique Lodel

theme:
    name: readthedocs
    
pages:
- Accueil: 'index.md'
- Installation complète de Lodel: 'installer lodel.md'
- 'Architecture et organisation.md'
- 'Modèle éditorial.md'

- LES CONTENUS STRUCTURES:
  - 'Les-contenus-structurés/XML.md'
  - 'Les-contenus-structurés/Schéma TEI.md'
  - 'Les-contenus-structurés/Schéma METS.md'
 
- LA CHAINE DE PUBLICATION WORD:
  - La chaine de publication XML (métopes): 'Métopes.md'
  - 'La-chaine-de-publication-Word/Modèle de document Microsoft Word.md'
  - 'La-chaine-de-publication-Word/Modèle de document Openoffice.md'
  - Conversion de fichiers OTX: 'La-chaine-de-publication-Word/OTX.md'

- LES TEMPLATES:
  - Introduction au modèle: 'Les-templates/Templates.md'
  - 'Les-templates/Lodelscript.md'

- Les extensions (plugins): 'Plugins.md'
- 'Les-templates/Exemple plugin.md'

- PROCEDURES DE MIGRATION:
  - 'Historique/De la version 0.8 à la 0.9.md'
  - 'Historique/De la version 0.9 à la 1.0.md'
  - 'Historique/Migration de la version 0.7 à 0.9 : un cas concret.md'

- HISTORIQUE DES RELEASES:
  - 'Historique/Release note de Lodel 0.8.md'
  - 'Historique/Release note de Lodel 0.8.1.md'
  - 'Historique/Release note de Lodel 0.8.2.md'
  - 'Historique/Release note de Lodel 0.8.7.md'
  - 'Historique/Release note de Lodel 0.9 RC1.md'
  - 'Historique/Release note de Lodel 0.9 RC2.md'
  - 'Historique/Release note de Lodel 0.9 RC3.md'
  - 'Historique/Release note de Lodel 0.9 RC4.md'
  - 'Historique/Release note de Lodel 0.9 stable.md'
  - 'Historique/Release note de Lodel 1.0 et OTX 1.0.md'
